1 Write a Python program to print the NumPy  version in your system.

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


2. Write a Python program to reverse an array  (first element becomes last). 

In [4]:
import numpy as np
arr = [10, 20, 30, 40, 50]
print(arr)
 
res = arr[::-1] 
print(res)


[10, 20, 30, 40, 50]
[50, 40, 30, 20, 10]


3.Write a Python program to convert a list and  tuple into arrays.

In [5]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))


List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


4.Write a Python program to find common values  between two arrays.

In [6]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


5.Write a Python program compare two arrays  using numpy. 

In [7]:
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


6.Write a Python program to change the  dimension of an array.

In [8]:
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


7.Write a Python program (using numpy) to sum  of all the multiples of 3 or 5 below 100.

In [9]:
x = np.arange(1, 100)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


Write a Python program to convert a NumPy  array into Python list structure. 

In [10]:
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


9. Write a Python program to how to add an extra  column to a numpy array. 

In [14]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


10∙ Write a Python program to check whether the  numpy array is empty or not. 

In [15]:
x = np.array([2, 3])
y = np.array([])
# size 2, array is not empty
print(x.size)
# size 0, array is empty
print(y.size)

2
0


11∙ Write a Python program to normalize a 3x3  random matrix. 

In [16]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.51543806 0.98127782 0.3646179 ]
 [0.96943146 0.52348096 0.17068036]
 [0.52299076 0.55111712 0.38128893]]
After normalization:
[[0.42531307 1.         0.23925258]
 [0.98538563 0.43523526 0.        ]
 [0.43463052 0.46932883 0.25981893]]


12∙ How to ignore all numpy warnings (not  recommended)? 

In [17]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan

In [18]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [20]:
np.nanmedian(data, axis=[1, 2])

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

13∙ How to swap two rows of an array? 

In [21]:
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]


In [22]:
a[[0, 2]] = a[[2, 0]]
print(a)

[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


14∙ Compute bootstrapped 95% confidence  intervals for the mean of a 1D array X (i.e.,  resample the elements of an array with  replacement N times, compute the mean of  each sample, and then compute percentiles  over the means). 

15∙ Python program to create a random vector of  size 10 and sort it.

In [23]:
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.02051441 0.6475948  0.425838   0.38021279 0.86229215 0.89104602
 0.59199158 0.78623546 0.22006873 0.06100856]
Sorted array:
[0.02051441 0.06100856 0.22006873 0.38021279 0.425838   0.59199158
 0.6475948  0.78623546 0.86229215 0.89104602]


16∙ Write a Python program to check two random  arrays are equal or not. 

In [24]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 0 1 1]
Second array:
[0 1 1 1 0 1]
Test above two arrays are equal or not!
False


17∙ Write a Python program to add, subtract,  multiply, divide arguments element-wise. ∙ Write a Python program to get the dates of  yesterday, today and tomorrow.

In [25]:
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25
